# Generated by Django 5.2.4 on 2025-11-10 04:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuadrilla',
            options={'ordering': ['nombre'], 'verbose_name': 'Cuadrilla', 'verbose_name_plural': 'Cuadrillas'},
        ),
        migrations.AlterModelOptions(
            name='integrante',
            options={'ordering': ['nombre'], 'verbose_name': 'Integrante', 'verbose_name_plural': 'Integrantes'},
        ),
        migrations.AlterModelOptions(
            name='proyecto',
            options={'ordering': ['-fecha_inicio'], 'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.AlterField(
            model_name='cuadrilla',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva')], default='activa', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='cuadrilla',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre de la cuadrilla'),
        ),
        migrations.AlterField(
            model_name='cuadrilla',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuadrillas', to='core.proyecto', verbose_name='Proyecto asignado'),
        ),
        migrations.AlterField(
            model_name='integrante',
            name='cargo',
            field=models.CharField(choices=[('operario', 'Operario'), ('ayudante', 'Ayudante'), ('supervisor', 'Supervisor'), ('lider', 'Líder de cuadrilla')], max_length=20, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='integrante',
            name='cuadrilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrantes', to='core.cuadrilla', verbose_name='Cuadrilla'),
        ),
        migrations.AlterField(
            model_name='integrante',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre del integrante'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='ciudad',
            field=models.CharField(max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='cliente',
            field=models.CharField(max_length=100, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='direccion',
            field=models.CharField(max_length=255, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('planificado', 'Planificado'), ('en_progreso', 'En progreso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='planificado', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_termino',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de término'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre del proyecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='presupuesto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Presupuesto (CLP)'),
        ),
    ]
