# Generated by Django 5.2.4 on 2025-11-10 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cuadrilla_options_alter_integrante_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='presupuesto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
