# Generated by Django 5.2.4 on 2025-11-10 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_proyecto_presupuesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuadrilla',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuadrilla', to='core.proyecto', verbose_name='Proyecto asignado'),
        ),
    ]
