# Generated by Django 5.2.4 on 2025-11-10 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_cuadrilla_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrante',
            name='cuadrilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integrantes', to='core.cuadrilla', verbose_name='Cuadrilla'),
        ),
    ]
