# Generated by Django 5.2.4 on 2025-11-10 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_integrante_cuadrilla'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integrante',
            name='cuadrilla',
        ),
    ]
