# Generated by Django 5.2.4 on 2025-11-10 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_integrante_cuadrilla'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuadrilla',
            name='integrantes',
            field=models.ManyToManyField(related_name='cuadrillas', to='core.integrante', verbose_name='Integrantes'),
        ),
        migrations.AlterField(
            model_name='cuadrilla',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuadrillas', to='core.proyecto', verbose_name='Proyecto asignado'),
        ),
    ]
