# Generated by Django 5.2.4 on 2025-11-10 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cuadrilla_integrantes_alter_cuadrilla_proyecto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuadrilla',
            name='integrantes',
        ),
        migrations.AddField(
            model_name='integrante',
            name='cuadrilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integrantes', to='core.cuadrilla'),
        ),
    ]
