# Generated by Django 5.2.4 on 2025-11-18 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_cuadrilla_integrantes_integrante_cuadrilla'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrante',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('asignado', 'Asignado'), ('licencia', 'En licencia'), ('suspendido', 'Suspendido')], default='disponible', max_length=15, verbose_name='Estado del trabajador'),
        ),
        migrations.AddField(
            model_name='integrante',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='integrante',
            name='notas',
            field=models.TextField(blank=True, verbose_name='Notas internas'),
        ),
        migrations.CreateModel(
            name='CambioCuadrilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('creacion', 'Creación'), ('actualizacion', 'Actualización'), ('reasignacion', 'Reasignación'), ('estado', 'Cambio de estado')], max_length=20, verbose_name='Tipo de acción')),
                ('descripcion', models.TextField(verbose_name='Detalle del cambio')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cuadrilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios', to='core.cuadrilla')),
            ],
            options={
                'verbose_name': 'Cambio de cuadrilla',
                'verbose_name_plural': 'Cambios de cuadrilla',
                'ordering': ['-fecha'],
            },
        ),
    ]
