# Generated by Django 5.2.8 on 2025-11-21 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_make_integrante_usuario_required'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='integrante',
            options={'ordering': ['usuario__first_name', 'usuario__last_name'], 'verbose_name': 'Integrante', 'verbose_name_plural': 'Integrantes'},
        ),
    ]
