# Generated by Django 5.2.8 on 2025-11-29 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_integrante_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='integrante',
            options={'ordering': ['nombre_trabajador', 'apellido_trabajador', 'usuario__first_name', 'usuario__last_name'], 'verbose_name': 'Integrante', 'verbose_name_plural': 'Integrantes'},
        ),
        migrations.AddField(
            model_name='cuadrilla',
            name='trabajador',
            field=models.ForeignKey(blank=True, limit_choices_to={'cargo': 'lider'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuadrillas_lideradas', to='core.integrante', verbose_name='Líder de cuadrilla'),
        ),
        migrations.AddField(
            model_name='integrante',
            name='apellido_trabajador',
            field=models.CharField(blank=True, max_length=100, verbose_name='Apellido'),
        ),
        migrations.AddField(
            model_name='integrante',
            name='nombre_trabajador',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='integrante',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integrante', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.CreateModel(
            name='SolicitudReasignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo de la solicitud')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('cuadrilla_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_entrada', to='core.cuadrilla', verbose_name='Cuadrilla destino')),
                ('cuadrilla_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_salida', to='core.cuadrilla', verbose_name='Cuadrilla origen')),
                ('respondido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_respondidas', to=settings.AUTH_USER_MODEL, verbose_name='Respondido por')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_reasignacion', to='core.integrante', verbose_name='Trabajador')),
            ],
            options={
                'verbose_name': 'Solicitud de Reasignación',
                'verbose_name_plural': 'Solicitudes de Reasignación',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
