# Generated by Django 5.2.4 on 2025-11-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_integrante_options_cuadrilla_trabajador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrante',
            name='licencia_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Fin de licencia'),
        ),
        migrations.AddField(
            model_name='integrante',
            name='licencia_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Inicio de licencia'),
        ),
    ]
