# Generated by Django 5.2.4 on 2025-12-05 02:49

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_integrante_licencia_fin_integrante_licencia_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrante',
            name='especialidad',
            field=models.CharField(blank=True, choices=[('electricista', 'Electricista'), ('albanil', 'Albañil'), ('fontanero', 'Fontanero'), ('pintor', 'Pintor'), ('carpintero', 'Carpintero'), ('jornal', 'Jornal'), ('otro', 'Otro')], max_length=20, null=True, verbose_name='Especialidad'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre del proyecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='presupuesto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddConstraint(
            model_name='cuadrilla',
            constraint=models.UniqueConstraint(fields=('nombre',), name='unique_cuadrilla_nombre'),
        ),
        migrations.AddConstraint(
            model_name='proyecto',
            constraint=models.UniqueConstraint(fields=('nombre',), name='unique_proyecto_nombre'),
        ),
    ]
