# Generated by Django 5.2.4 on 2025-12-05 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_integrante_especialidad_alter_proyecto_nombre_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialCuadrilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la cuadrilla')),
                ('proyecto_nombre', models.CharField(max_length=100, verbose_name='Nombre del proyecto')),
                ('proyecto_id', models.IntegerField(verbose_name='ID del proyecto')),
                ('lider_nombre', models.CharField(blank=True, max_length=100, verbose_name='Nombre del líder')),
                ('estado', models.CharField(max_length=10, verbose_name='Estado')),
                ('fecha_eliminacion', models.DateTimeField(auto_now_add=True)),
                ('integrantes_cantidad', models.IntegerField(default=0, verbose_name='Cantidad de integrantes')),
                ('notas', models.TextField(blank=True, verbose_name='Notas del historial')),
                ('eliminado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuadrillas_eliminadas', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
            ],
            options={
                'verbose_name': 'Historial de cuadrilla',
                'verbose_name_plural': 'Historial de cuadrillas',
                'ordering': ['-fecha_eliminacion'],
            },
        ),
    ]
