# Generated by Django 5.2.4 on 2025-12-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_historialcuadrilla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cambiocuadrilla',
            name='accion',
            field=models.CharField(choices=[('creacion', 'Creación'), ('actualizacion', 'Actualización'), ('reasignacion', 'Reasignación'), ('estado', 'Cambio de estado'), ('eliminacion', 'Eliminación')], max_length=20, verbose_name='Tipo de acción'),
        ),
        migrations.DeleteModel(
            name='HistorialCuadrilla',
        ),
    ]
