# Generated by Django 5.2.4 on 2025-12-05 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_cambiocuadrilla_accion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cambiocuadrilla',
            name='cuadrilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios', to='core.cuadrilla'),
        ),
    ]
